### ISSUE TITLE
OCR image-only PDFs

### ISSUE THREAD

**Issue by seth-shaw-unlv** [Islandora/documentation#1583]
Stemming from on [an email discussion](https://groups.google.com/g/islandora-dev/c/oPr1ZsJx-HA):

Hypercube currently uses pdftotext to extract text embedded in a PDF OR tesseract to perform OCR on images. However, if a user uploads a scanned document as a PDF, it won't perform OCR on the scanned document resulting in no output. 

Tesseract can't process PDFs natively (ergo the pdftotext) but we can use [pdfimages](https://manpages.debian.org/testing/poppler-utils/pdfimages.1.en.html) to extract the images into a temporary directory and loop tesseract over those to produce our extracted text OCR.

**Comment by DonRichards** [comment]
Is this still an issue?

**Comment by seth-shaw-unlv** [comment]
I *think* so. Tagging as a feature request until someone can confirm we have PDF OCR.

**Comment by DonRichards** [comment]
It should be working. Our installation of it has it working

**Comment by seth-shaw-unlv** [comment]
@DonRichards, and it isn't a Born-Digital specific feature? Can you test on a vanilla Islandora install to confirm?

**Comment by DonRichards** [comment]
I think this is still a problem after testing on my local.

**Comment by rosiel** [comment]
This is still an issue. When Hypercube gets a PDF, it uses pdftotext instead. This was done as part of the RDM work.

We did not realize that you can get text out of most text-containing files (and if you want into the solr index) with https://www.drupal.org/project/file_extractor.

I have a PR coming after I run the tests.

**Comment by rosiel** [comment]
I do not have a PR coming. It turns out Hypercube on its own does not accept PDFs, you need a wrapper like [ocrmypdf](https://github.com/ocrmypdf/OCRmyPDF).

**Comment by DonRichards** [comment]
Linked to this as well https://github.com/Islandora/documentation/issues/1012

**Comment by adam-vessey** [comment]
Popped up in the `islandora/islandora` queue: https://github.com/Islandora/islandora/issues/910
